### ISSUE TITLE
GTK4 port?

### ISSUE THREAD

**Issue by bertob** [manuvarkey/GElectrical#10]
Just stumbled across this app, looks very cool! I'm curious though why it's using GTK3 even though it seems to be quite new. Do you have plans to port to GTK4? Are there any blockers from the platform side?

**Comment by manuvarkey** [comment]
Hi @bertob,

The app development started with GTK3. At that time, the API for GTK4 was not stable and proper documentation was not available for use on `python`. 

Also since this is meant to be a multi platform application, windows build is a major concern. Building GTK3 on windows was a tedious process and I got it working after much effort. `MSYS2` was not working since the project depends on certain python packages which did not have wheels build for `MSYS2`. Finally got the setup working with `gvsbuild` after some effort. A prebuilt installable SDK will make GTK adoption much more easier.

Porting to GTK4 seems like a lot of work. Too many API changes from GTK3. Will try to make the shift gradually.

**Comment by bertob** [comment]
Makes sense, thanks for the context! I know at least a few GTK4 apps that ship Windows builds (e.g. [Gaphor])(https://github.com/gaphor/gaphor), but yes, in general the developer story for Windows is not ideal. If you have any GTK4 porting / Windows support questions, [this Matrix room](https://matrix.to/#/#app-dev:gnome.org) might come in handy :)
